import pool from '../config/db.js';
import { generateAIStudyRoadmap } from '../services/geminiService.js';

/**
 * Generate a new study roadmap using the Gemini service and save it to the DB
 */
export async function generateRoadmap(req, res) {
  const { target_company, days_available } = req.body;
  const userId = req.user.id;

  // Validate inputs
  if (!target_company || !days_available) {
    return res.status(400).json({
      success: false,
      message: 'Please provide both the target company and the number of days available.'
    });
  }

  const days = parseInt(days_available, 10);
  if (isNaN(days) || days <= 0) {
    return res.status(400).json({
      success: false,
      message: 'Days available must be a valid positive integer.'
    });
  }

  try {
    // Calculate number of weeks (minimum of 1 week)
    const weeks = Math.max(1, Math.ceil(days / 7));

    // Generate roadmap data from AI Service
    const roadmapData = await generateAIStudyRoadmap(target_company, weeks);

    // Insert the roadmap into the database
    const insertQuery = `
      INSERT INTO roadmaps (user_id, target_company, days_available, roadmap_data)
      VALUES ($1, $2, $3, $4::jsonb)
      RETURNING *
    `;
    const result = await pool.query(insertQuery, [
      userId,
      target_company,
      days,
      JSON.stringify(roadmapData)
    ]);

    res.status(201).json({
      success: true,
      roadmap: result.rows[0]
    });
  } catch (error) {
    console.error('Error generating study roadmap:', error.message);
    res.status(500).json({
      success: false,
      message: 'Server error: Failed to generate placement study roadmap.'
    });
  }
}

/**
 * Retrieve all previous roadmaps generated by the logged-in student
 */
export async function getRoadmaps(req, res) {
  const userId = req.user.id;

  try {
    const selectQuery = `
      SELECT * FROM roadmaps
      WHERE user_id = $1
      ORDER BY created_at DESC
    `;
    const result = await pool.query(selectQuery, [userId]);

    res.status(200).json({
      success: true,
      roadmaps: result.rows
    });
  } catch (error) {
    console.error('Error retrieving roadmaps:', error.message);
    res.status(500).json({
      success: false,
      message: 'Server error: Failed to fetch study roadmaps.'
    });
  }
}

/**
 * Delete a specific roadmap
 */
export async function deleteRoadmap(req, res) {
  const { id } = req.params;
  const userId = req.user.id;

  try {
    const deleteQuery = `
      DELETE FROM roadmaps
      WHERE id = $1 AND user_id = $2
      RETURNING *
    `;
    const result = await pool.query(deleteQuery, [id, userId]);

    if (result.rows.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'Roadmap not found or unauthorized to delete.'
      });
    }

    res.status(200).json({
      success: true,
      message: 'Roadmap deleted successfully.',
      roadmap: result.rows[0]
    });
  } catch (error) {
    console.error('Error deleting roadmap:', error.message);
    res.status(500).json({
      success: false,
      message: 'Server error: Failed to delete roadmap.'
    });
  }
}
